### ISSUE TITLE
Make "bg" parameter optional (or let it set a color)

### ISSUE THREAD

**Issue by vas3k** [nDmitry/ogimgd#2]
Not all posts have a background image. This one, for example:

```
https://i.rationalanswer.club/preview/?icon=https%3A%2F%2Fvas3k.club%2Fstatic%2Fimages%2Flogo%2Flogo-256.png&op=0.4&label_l=%D0%92%D0%B0%D1%81%D1%82%D1%80%D0%B8%D0%BA&label_r=%D0%9A%D0%BB%D1%83%D0%B1&title=%D0%9D%D0%B5%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE+%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%B5%2C+%D0%BD%D0%BE+%D0%BD%D0%B5%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5+%D0%BC%D0%B8%D1%80%D1%83+%D1%82%D1%83%D0%BB%D0%B7%D1%8B&author=ArtemGolovin&ava=https%3A%2F%2Fi.vas3k.club%2Fna.jpg&bg=https%3A%2F%2Fvas3k.club%2Fstatic%2Fimages%2Fshare.png
```

However, the "bg" param is mandatory. I could use a blank white picture as the background, but that's kind of hacky. It would be nice to make this parameter optional (and use white by default) OR make it accept hex color like "FFFFFF" in addition to URL.

**Comment by nDmitry** [comment]
I thought there will be some default background you would use in case of a post pic is missing, but a blank color is also fine by me. Will do.
